SELECT_COMMAND = 'SELECT {} FROM {} WHERE Id = {}'
SELECT_COMMAND_WITHOUT_WHERE = 'SELECT {} FROM {}'
SELECT_COMMAND_ONLY_WHERE = 'SELECT {} FROM {} WHERE {}'
UPDATE_COMMAND = 'UPDATE Account SET Amount = Amount {} {} WHERE Id = {}'
